import Head from 'next/head'
import Image from 'next/image'
import { Typewriter } from 'react-simple-typewriter'
import profilePic from '../public/dev-ed-wave.png';
import Design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import {AiFillTwitterCircle ,AiFillLinkedin,AiFillYoutube} from 'react-icons/ai';
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import { BsFillBrightnessHighFill } from "react-icons/bs";
import {BsFillMoonStarsFill} from "react-icons/bs";
import web6 from '../public/web6.png'
import {useState} from 'react'
export default function Home() {
  const[darkmode,setDarckmode]=useState(false);

  function Uselight(props) {
    return  <BsFillBrightnessHighFill onClick={()=> setDarckmode(!darkmode)} className='cursor-pointer text-2xl'/>;

  }
  
  function Usedarck(props) {
    return <BsFillMoonStarsFill onClick={()=> setDarckmode(!darkmode)} className='cursor-pointer text-2xl'/>;
     
  }
function Greeting(props) {
  
  if (darkmode) {
    return <Uselight />;
  }
  return <Usedarck/>;
}


  return (
    <div className={darkmode ? 'dark' : ""}>
      <Head>
        <title>Mr.x</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='select-none bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 '>
      <section className='min-h-screen'>
      <nav className='py-10 mb-12 flex justify-between'>
        <h1 className='text-xl font-burtons mr-5 dark:text-teal-700'>developedbymrx</h1>
        <ul className='flex items-center'>
          <li>
            <Greeting/>
            
            </li>
          <li><a href="http://" className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded ml-8'>Resume</a> </li>
        </ul>
      </nav>
      <div className='text-center p-10'>
     
        <p className='text-md py-5 leading-3 text-gray-800 dark:text-gray-400'>hi, I'm</p>
        <h2 className='text-2xl py-2 text-teal-600 font-medium font-exo lg:text-5xl'>
        <Typewriter 
      loop
      cursor
      cursorStyle='|'
      words={["Mouad Ait Naim"]}
      />
        </h2>

        <h3 className='text-2xl py-2 dark:text-white'>A Web Developer</h3>
        <p className='text-md py-5 leading-3 text-gray-800'>#wordpress #java #react #css #html </p>
      </div>
      <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
          <AiFillTwitterCircle className='hover:text-teal-500 cursor-pointer'/>
          <AiFillLinkedin className='hover:text-teal-500 cursor-pointer'/>
          <AiFillYoutube className='hover:text-teal-500 cursor-pointer'/>
      </div>
    <div className='relative mx-auto mz-20 
    overflow-hidden
     bg-gradient-to-b from-teal-500 
     rounded-full 
     w-80 h-80 mt-20 md:h-96 md:w-96'>
    <Image 
    style={{width: '400px', height: '300px'}}
        src={profilePic}
        layout='fill'
        objectFit="cover"
        
      />
    </div>
    </section>
  <section>
    <div >
      <h3 className='text-3xl py-1 dark:text-white'>C'est qui Mouad ?</h3>
    <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
    Salut je m'appele <span className='text-teal-500'>Mouad</span> je suis un devloper qui aime son travail,
     j'ai un certificat <span className='text-teal-500'>TSDI</span> "Technicien Spécialisé en Développement Informatique", durant mais étude j'ai créé plusieurs projets pour résoudre des problèmes basés sur le langage <span className='text-teal-500'>java</span> connecter
      avec un system de gestion de données <span className='text-teal-500'>mysql</span> pour faciliter la tâche de triter et  
    sauvegarder les données, Par ailleurs j'ai aussi créé des sites web e-Com sur la plateforme <span className='text-teal-500'>shopyfay.</span>
    </p>
    <p className='text-gray-800 text-md leading-8 dark:text-gray-400'>
    J'offre la conception des sites Web, application mobile et application de bureau.
    </p>
    </div>
    <div className='lg:flex  gap-5'>

<div className='text-center shadow-lg p-10 rounded-xl my-10 pb-2  dark:bg-gray-50 dark:shadow-lg dark:shadow-teal-500'>
    <Image className='mx-auto' src={Design} height={100} width={100}/>
    <h3 className='text-lg font-medium pt-8'>Joli Design</h3>
    <p className='py-2 mr-5 ml-5'>Créez un design élégant qui correspond à votre théorie du design</p>
    <h4 className='py-4 text-teal-600'>
    Les outils de conception que j'utilise
    </h4>
    <p className='text-gray-800 py-1'>Photoshop</p>
    <p className='text-gray-800 py-1'>Illustrator</p>
</div>

<div className='text-center shadow-lg p-10 rounded-xl my-10 pb-4 dark:bg-gray-50 dark:shadow-lg dark:shadow-teal-500'>
    <Image className='mx-auto' src={code} height={100} width={100}/>
    <h3 className='text-lg font-medium pt-8 pb-8'>Codage {'<'}.../{'>'} </h3>
    <p className='py-2'>Je cherche toujours dans les nouvelles
     technologie pour le meilleure
      performance de mais projet </p>
    {/* <h4 className='py-4 text-teal-600'>
      Design Tools I use
    </h4>
    <p className='text-gray-800 py-1'>Photoshop</p>
    <p className='text-gray-800 py-1'>Illustrator</p> */}
</div>


<div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-50 dark:shadow-lg dark:shadow-teal-500'>
    <Image className='mx-auto' src={consulting} height={100} width={100}/>
    <h3 className='text-lg font-medium pt-8 pb-2'>Code De Votre Projet De Rêve</h3>
    <p className='py-2'>Avez-vous une idée pour votre prochain grand site Web ou application ? Rendons-le réel</p>
    {/* <h4 className='py-4 text-teal-600'>
      Design Tools I use
    </h4>
    <p className='text-gray-800 py-1'>Photoshop</p>
    <p className='text-gray-800 py-1'>Illustrator</p> */}
</div>



</div>

  </section>
  <section>
    <div>
      <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
      <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
      Un des projets qui me rendent fier 
<span className='text-teal-500'>Blue Moon </span>
 C'est une application Desktop pour la Ministère des habous et des affaires islamiques pour la gestion des données, et le projet <span className='text-teal-500'> 
 Apocalypse </span> C'est une application Desktop aussi mais pour les écoles 
    </p>
    <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap '>
<div className='basis-1/3 flex-1'>
  <Image className='rounded-lg object-cover' src={web1} layout='responsive' />
</div>
<div className='basis-1/3 flex-1'>
  <Image className='rounded-lg object-cover' src={web2} layout='responsive' />
</div>
<div className='basis-1/3 flex-1'>
  <Image className='rounded-lg object-cover' src={web3} layout='responsive' />
</div>
<div className='basis-1/3 flex-1'>
  <Image className='rounded-lg object-cover' src={web4} layout='responsive' />
</div>
<div className='basis-1/3 flex-1'>
  <Image className='rounded-lg object-cover' src={web5} layout='responsive' />
</div>
<div className='basis-1/3 flex-1'>
  <Image className='rounded-lg object-cover' src={web6} layout='responsive' />
</div>
    </div>
    </div>
  </section>
     </main>

     
    </div>
  )
}
